// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team_Golf;

namespace Team_Golf.Migrations
{
    [DbContext(typeof(GolfCourseContext))]
    partial class GolfCourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Team_Golf.Models.GolfCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GolfCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "Bushwood.jpg",
                            Name = "Bushwood CC",
                            Review = "Good snack shack and poor caddying"
                        },
                        new
                        {
                            Id = 2,
                            Image = "FurryCreek.jpg",
                            Name = "Fury Creek Golf CC",
                            Review = "Price is wrong B&$#%"
                        },
                        new
                        {
                            Id = 3,
                            Image = "Cottonwood.jpg",
                            Name = "Cotton Wood",
                            Review = "Waggle and let the big dog eat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
